import { convexTest } from "convex-test"
import { describe, expect, it } from "vitest"
import { ConvexError } from "convex/values"
import { api } from "./_generated/api"
import { companyIdentity } from "./lib/testIdentity"
import schema from "./schema"

const modules = import.meta.glob("./**/*.{ts,js}")
const setup = () => convexTest(schema, modules).withIdentity(companyIdentity)
async function errorCode(promise: Promise<unknown>, code: string) {
  try { await promise; throw new Error("Expected rejection") } catch (error) {
    expect(error).toBeInstanceOf(ConvexError)
    expect((error as ConvexError<{ code: string }>).data.code).toBe(code)
  }
}

describe("Convex contacts", () => {
  it("cleans fields, derives names, normalizes email and returns shared records", async () => {
    const t = setup()
    const c = await t.mutation(api.contacts.create, { input: { firstName: " Ada ", lastName: " Lovelace ", email: " Ada@Example.com ", notes: " " } })
    expect(c).toMatchObject({ kind: "individual", displayName: "Ada Lovelace", email: "Ada@Example.com", emailNormalized: "ada@example.com", notes: null, archivedAt: null })
    expect(c).not.toHaveProperty("_id")
    expect(await t.query(api.contacts.getById, { id: c.id })).toEqual(c)
    const company = await t.mutation(api.contacts.create, { input: { kind: "organization", organizationName: " Venue " } })
    expect(company.displayName).toBe("Venue")
    await errorCode(t.mutation(api.contacts.create, { input: {} }), "InvalidInput")
    await errorCode(t.mutation(api.contacts.create, { input: { displayName: "Bad", email: "invalid" } }), "InvalidInput")
  })
  it("enforces active email uniqueness with an existing contact ID", async () => {
    const t = setup()
    const c = await t.mutation(api.contacts.create, { input: { displayName: "Ada", email: "ada@example.com" } })
    await expect(t.mutation(api.contacts.create, { input: { displayName: "Duplicate", email: "ADA@example.com" } })).rejects.toMatchObject({ data: { code: "EmailTaken", existingContactId: c.id } })
    const other = await t.mutation(api.contacts.create, { input: { displayName: "Other" } })
    await errorCode(t.mutation(api.contacts.update, { id: other.id, patch: { email: "ADA@example.com" } }), "EmailTaken")
    await t.mutation(api.contacts.archive, { id: c.id })
    await t.mutation(api.contacts.archive, { id: c.id })
    await t.mutation(api.contacts.update, { id: other.id, patch: { email: "ADA@example.com" } })
    await errorCode(t.mutation(api.contacts.restore, { id: c.id }), "EmailTaken")
    await t.mutation(api.contacts.update, { id: other.id, patch: { email: null } })
    await t.mutation(api.contacts.restore, { id: c.id })
    await t.mutation(api.contacts.restore, { id: c.id })
    expect((await t.query(api.contacts.getById, { id: c.id }))?.archivedAt).toBeNull()
  })
  it("updates derived names, preserves custom names, and rejects immutable fields", async () => {
    const t = setup()
    const c = await t.mutation(api.contacts.create, { input: { firstName: "Ada" } })
    expect((await t.mutation(api.contacts.update, { id: c.id, patch: { lastName: "Lovelace" } })).displayName).toBe("Ada Lovelace")
    await t.mutation(api.contacts.update, { id: c.id, patch: { displayName: "Countess" } })
    const updated = await t.mutation(api.contacts.update, { id: c.id, patch: { firstName: "Augusta", notes: " notes " } })
    expect(updated).toMatchObject({ displayName: "Countess", notes: "notes", createdAt: c.createdAt })
    // @ts-expect-error Untrusted renderer field.
    await expect(t.mutation(api.contacts.update, { id: c.id, patch: { archivedAt: "fake" } })).rejects.toThrow()
    await t.mutation(api.contacts.remove, { id: c.id })
    expect(await t.query(api.contacts.getById, { id: c.id })).toBeNull()
    await errorCode(t.mutation(api.contacts.update, { id: c.id, patch: {} }), "NotFound")
    await errorCode(t.mutation(api.contacts.archive, { id: c.id }), "NotFound")
    await errorCode(t.mutation(api.contacts.restore, { id: c.id }), "NotFound")
    await errorCode(t.mutation(api.contacts.remove, { id: c.id }), "NotFound")
  })
  it("searches literal substrings, filters roles/categories/archive and uses stable scoped cursors", async () => {
    const t = setup()
    const a = await t.mutation(api.contacts.create, { input: { displayName: "A%_", phone: "12345" } })
    const b = await t.mutation(api.contacts.create, { input: { displayName: "B", organizationName: "Group", email: "b@example.com" } })
    const c = await t.mutation(api.contacts.create, { input: { displayName: "C" } })
    await t.mutation(api.contacts.archive, { id: c.id })
    const category = await t.mutation(api.vendorCategories.create, { input: { key: "test", label: "Test", colorToken: "teal" } })
    await t.mutation(api.contactRoles.ensure, { contactId: b.id, role: "vendor", vendorCategoryId: category.id })
    const first = await t.query(api.contacts.search, { limit: 1 })
    expect(first.items.map(c => c.id)).toEqual([a.id])
    await t.mutation(api.contacts.create, { input: { displayName: "A!" } })
    const second = await t.query(api.contacts.search, { limit: 1, cursor: first.nextCursor })
    expect(second.items.map(c => c.id)).toEqual([b.id])
    expect(second.nextCursor).toBeNull()
    for (const query of ["%_", "234", "group", "B@EXAMPLE"]) expect((await t.query(api.contacts.search, { limit: 100, query })).items).toHaveLength(1)
    const filtered = await t.query(api.contacts.search, { limit: 100, vendorCategoryId: category.id })
    expect(filtered.items.map(c => c.id)).toEqual([b.id])
    expect(filtered.items[0]?.roles[0]?.vendorCategory?.id).toBe(category.id)
    expect((await t.query(api.contacts.search, { limit: 100, role: "client" })).items).toEqual([])
    expect((await t.query(api.contacts.search, { limit: 100, includeArchived: true })).items).toHaveLength(4)
    await errorCode(t.query(api.contacts.search, { limit: 1, query: "different", cursor: first.nextCursor }), "InvalidInput")
    await errorCode(t.query(api.contacts.search, { limit: 1, cursor: "bad" }), "InvalidInput")
  })
  it("merges roles, active duplicates, removed history and missing shared fields", async () => {
    const t = setup()
    const source = await t.mutation(api.contacts.create, { input: { displayName: "Source", email: "source@example.com", phone: "123", notes: "Details" } })
    const target = await t.mutation(api.contacts.create, { input: { displayName: "Target" } })
    const event = await t.mutation(api.events.create, { input: {} })
    const original = await t.mutation(api.eventContacts.assign, { eventId: event.id, target: { contactId: source.id }, role: "client", opts: { isPrimary: true, notes: "Arrival" } })
    const duplicate = await t.mutation(api.eventContacts.assign, { eventId: event.id, target: { contactId: target.id }, role: "client" })
    const removed = await t.mutation(api.eventContacts.assign, { eventId: event.id, target: { contactId: source.id }, role: "coordinator" })
    await t.mutation(api.eventContacts.remove, { id: removed.id })
    const merged = await t.mutation(api.contacts.merge, { sourceId: source.id, targetId: target.id })
    expect(merged).toMatchObject({ email: source.email, emailNormalized: source.emailNormalized, phone: "123", notes: "Details" })
    expect((await t.query(api.contacts.getById, { id: source.id }))?.archivedAt).toBeTruthy()
    expect(await t.query(api.contactRoles.listForContact, { contactId: source.id })).toEqual([])
    expect(await t.query(api.contactRoles.listForContact, { contactId: target.id })).toHaveLength(2)
    const history = await t.query(api.eventContacts.listEventsForContact, { contactId: target.id })
    expect(history).toHaveLength(2)
    expect(history.find(r => r.eventContactId === duplicate.id)).toMatchObject({ isPrimary: true })
    expect(history.find(r => r.eventContactId === removed.id)?.removedAt).toBeTruthy()
    expect(await t.run(ctx => ctx.db.get("eventContacts", original.id))).toBeNull()
    expect((await t.query(api.eventContacts.getPanel, { eventId: event.id })).groups[0]?.items[0]).toMatchObject({ notes: "Arrival", contactId: target.id })
    await errorCode(t.mutation(api.contacts.merge, { sourceId: target.id, targetId: target.id }), "InvalidInput")
    await t.mutation(api.contacts.archive, { id: target.id })
    await errorCode(t.mutation(api.contacts.merge, { sourceId: source.id, targetId: target.id }), "ContactArchived")
  })
  it("hard deletion removes standing roles but refuses even removed event history", async () => {
    const t = setup()
    const c = await t.mutation(api.contacts.create, { input: { displayName: "Test" } })
    await t.mutation(api.contactRoles.ensure, { contactId: c.id, role: "client" })
    await t.mutation(api.contacts.remove, { id: c.id })
    expect(await t.query(api.contactRoles.listForContact, { contactId: c.id })).toEqual([])
    const event = await t.mutation(api.events.create, { input: {}, client: { displayName: "Client" } })
    const assignment = (await t.run(ctx => ctx.db.query("eventContacts").withIndex("by_event", q => q.eq("eventId", event.id)).first()))!
    await t.mutation(api.eventContacts.remove, { id: assignment._id })
    await errorCode(t.mutation(api.contacts.remove, { id: assignment.contactId }), "ContactInUse")
  })
  it("preserves populated merge targets and archived categories while moving distinct assignments", async () => {
    const t = setup()
    const source = await t.mutation(api.contacts.create, { input: { displayName: "Source", email: "source@example.com", phone: "source", notes: "source" } })
    const target = await t.mutation(api.contacts.create, { input: { displayName: "Target", email: "target@example.com", phone: "target", notes: "target" } })
    const category = await t.mutation(api.vendorCategories.create, { input: { key: "test", label: "Test", colorToken: "sky" } })
    const event = await t.mutation(api.events.create, { input: {} })
    const row = await t.mutation(api.eventContacts.assign, { eventId: event.id, target: { contactId: source.id }, role: "vendor", opts: { vendorCategoryId: category.id, isPrimary: true } })
    await t.mutation(api.vendorCategories.archive, { id: category.id })
    const merged = await t.mutation(api.contacts.merge, { sourceId: source.id, targetId: target.id })
    expect(merged).toMatchObject({ email: "target@example.com", phone: "target", notes: "target" })
    expect(await t.run(ctx => ctx.db.get("eventContacts", row.id))).toMatchObject({ contactId: target.id, isPrimary: true })
    expect(await t.query(api.contactRoles.listForContact, { contactId: target.id })).toHaveLength(1)
    await t.mutation(api.contacts.update, { id: target.id, patch: { email: undefined, phone: undefined } })
    expect((await t.query(api.contacts.getById, { id: target.id }))?.email).toBe("target@example.com")
  })

})

describe("Convex vendor categories and standing roles", () => {
  it("seeds idempotently, validates categories and preserves keys once in use", async () => {
    const t = setup()
    await t.mutation(api.vendorCategories.seedDefaults, {})
    await t.mutation(api.vendorCategories.seedDefaults, {})
    expect(await t.query(api.vendorCategories.getAll, {})).toHaveLength(8)
    const category = await t.mutation(api.vendorCategories.create, { input: { key: " TEST ", label: " Test ", colorToken: " sky ", sortOrder: 5 } })
    expect(category).toMatchObject({ key: "test", label: "Test", colorToken: "sky", sortOrder: 5 })
    await errorCode(t.mutation(api.vendorCategories.create, { input: { key: "test", label: "Duplicate", colorToken: "teal" } }), "InvalidInput")
    for (const input of [{ key: "bad-key", label: "Test", colorToken: "teal" }, { key: "other_key", label: " ", colorToken: "teal" }, { key: "other_key", label: "Test", colorToken: "teal", sortOrder: 0.5 }]) await errorCode(t.mutation(api.vendorCategories.create, { input }), "InvalidInput")
    expect((await t.mutation(api.vendorCategories.update, { id: category.id, patch: { key: "renamed", label: "Renamed" } })).key).toBe("renamed")
    const c = await t.mutation(api.contacts.create, { input: { displayName: "Vendor" } })
    const role = await t.mutation(api.contactRoles.ensure, { contactId: c.id, role: "vendor", vendorCategoryId: category.id })
    expect(await t.mutation(api.contactRoles.ensure, { contactId: c.id, role: "vendor", vendorCategoryId: category.id })).toEqual(role)
    await errorCode(t.mutation(api.vendorCategories.update, { id: category.id, patch: { key: "again" } }), "InvalidInput")
    await errorCode(t.mutation(api.contactRoles.ensure, { contactId: c.id, role: "vendor" }), "InvalidRoleCategory")
    await errorCode(t.mutation(api.contactRoles.ensure, { contactId: c.id, role: "client", vendorCategoryId: category.id }), "InvalidRoleCategory")
    await t.mutation(api.vendorCategories.archive, { id: category.id })
    await t.mutation(api.vendorCategories.archive, { id: category.id })
    expect(await t.query(api.vendorCategories.getAll, {})).toHaveLength(8)
    expect(await t.query(api.vendorCategories.getAll, { includeArchived: true })).toHaveLength(9)
    const other = await t.mutation(api.contacts.create, { input: { displayName: "Other" } })
    await errorCode(t.mutation(api.contactRoles.ensure, { contactId: other.id, role: "vendor", vendorCategoryId: category.id }), "InvalidInput")
    await t.mutation(api.vendorCategories.restore, { id: category.id })
    await t.mutation(api.contactRoles.remove, { contactId: c.id, role: "vendor", vendorCategoryId: category.id })
    await t.mutation(api.contactRoles.remove, { contactId: c.id, role: "vendor", vendorCategoryId: category.id })
    expect(await t.query(api.contactRoles.listForContact, { contactId: c.id })).toEqual([])
  })
})
