import { convexTest } from "convex-test"
import { describe, expect, it } from "vitest"
import { internal } from "./_generated/api"
import schema from "./schema"
const modules = import.meta.glob("./**/*.{ts,js}")
async function setup() {
  const t = convexTest(schema, modules)
  const event = await t.mutation(internal.events.create, { input: { title: "Dinner", startDateTime: "2026-10-10T00:00:00Z" } })
  const other = await t.mutation(internal.events.create, { input: { title: "Other", startDateTime: "2026-11-10T00:00:00Z" } })
  const category = await t.mutation(internal.vendorCategories.create, { input: { key: "test", label: "Test", colorToken: "teal" } })
  return { t, event, other, category }
}

describe("Convex event contacts", () => {
  it("assigns inline contacts atomically, ensures standing roles and keeps fixed panel groups", async () => {
    const { t, event, other, category } = await setup()
    expect((await t.query(internal.eventContacts.getPanel, { eventId: event.id })).groups.map(g => g.role)).toEqual(["client", "coordinator", "vendor"])
    const assignment = await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { newContact: { displayName: "Client", email: "c@example.com" } }, role: "client", opts: { isPrimary: true, roleLabel: " Lead ", notes: " Notes " } })
    expect(assignment).toMatchObject({ eventId: event.id, role: "client", isPrimary: true, roleLabel: "Lead", notes: "Notes", sortOrder: 0 })
    const panel = await t.query(internal.eventContacts.getPanel, { eventId: event.id })
    expect(panel.groups[0]?.items[0]).toMatchObject({ contactId: assignment.contactId, displayName: "Client", initials: "C", contactArchived: false })
    expect((await t.query(internal.eventContacts.getPanel, { eventId: other.id })).groups.every(g => g.items.length === 0)).toBe(true)
    expect(await t.query(internal.contactRoles.listForContact, { contactId: assignment.contactId })).toHaveLength(1)
    await expect(t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { contactId: assignment.contactId }, role: "client" })).rejects.toMatchObject({ data: { code: "DuplicateAssignment" } })
    await t.mutation(internal.vendorCategories.archive, { id: category.id })
    await expect(t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { newContact: { displayName: "Rejected" } }, role: "vendor", opts: { vendorCategoryId: category.id } })).rejects.toThrow()
    expect((await t.query(internal.contacts.search, { limit: 100 })).items).toHaveLength(1)
  })
  it("clears other primaries only within the same event and role; soft remove/reactivate preserves history", async () => {
    const { t, event, other } = await setup()
    const a = await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { newContact: { displayName: "Alpha" } }, role: "client", opts: { isPrimary: true, notes: "Keep" } })
    const b = await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { newContact: { displayName: "Beta" } }, role: "client", opts: { isPrimary: true } })
    const coordinator = await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { contactId: a.contactId }, role: "coordinator", opts: { isPrimary: true } })
    const otherClient = await t.mutation(internal.eventContacts.assign, { eventId: other.id, target: { contactId: a.contactId }, role: "client", opts: { isPrimary: true } })
    await t.mutation(internal.eventContacts.setPrimary, { id: a.id })
    const panel = await t.query(internal.eventContacts.getPanel, { eventId: event.id })
    expect(panel.groups[0]?.items.map(i => [i.eventContactId, i.isPrimary])).toEqual([[a.id, true], [b.id, false]])
    expect(panel.groups[1]?.items[0]?.isPrimary).toBe(true)
    expect((await t.query(internal.eventContacts.getPanel, { eventId: other.id })).groups[0]?.items[0]?.isPrimary).toBe(true)
    await t.mutation(internal.eventContacts.remove, { id: a.id })
    await t.mutation(internal.eventContacts.remove, { id: a.id })
    expect((await t.query(internal.eventContacts.getPrimaryClients, { eventIds: [event.id, other.id] }))[event.id]?.contactId).toBe(b.contactId)
    const restored = await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { contactId: a.contactId }, role: "client" })
    expect(restored).toMatchObject({ id: a.id, notes: "Keep", createdAt: a.createdAt, removedAt: null, isPrimary: false })
    await t.mutation(internal.contacts.archive, { id: a.contactId })
    expect((await t.query(internal.eventContacts.getPanel, { eventId: event.id })).groups[1]?.items[0]?.contactArchived).toBe(true)
    await expect(t.mutation(internal.eventContacts.assign, { eventId: other.id, target: { contactId: a.contactId }, role: "coordinator" })).rejects.toMatchObject({ data: { code: "ContactArchived" } })
    expect((await t.query(internal.eventContacts.listEventsForContact, { contactId: a.contactId }))[0]?.eventContactId).toBe(otherClient.id)
    await t.mutation(internal.eventContacts.remove, { id: coordinator.id })
    const history = await t.query(internal.eventContacts.listEventsForContact, { contactId: a.contactId })
    expect(history.find(r => r.eventContactId === coordinator.id)?.removedAt).toBeTruthy()
  })
  it("validates reorder exactly, updates assignment fields, and resolves primary fallback", async () => {
    const { t, event, other } = await setup()
    const a = await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { newContact: { displayName: "Alpha" } }, role: "client" })
    const b = await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { newContact: { displayName: "Beta" } }, role: "client" })
    await t.mutation(internal.eventContacts.reorder, { eventId: event.id, role: "client", orderedIds: [b.id, a.id] })
    expect((await t.query(internal.eventContacts.getPrimaryClients, { eventIds: [event.id, other.id] }))[event.id]?.contactId).toBe(b.contactId)
    expect((await t.query(internal.eventContacts.getPrimaryClients, { eventIds: [other.id] }))[other.id]).toBeUndefined()
    for (const orderedIds of [[], [a.id, a.id], [a.id]]) await expect(t.mutation(internal.eventContacts.reorder, { eventId: event.id, role: "client", orderedIds })).rejects.toMatchObject({ data: { code: "InvalidInput" } })
    await t.mutation(internal.eventContacts.update, { id: a.id, patch: { isPrimary: true, roleLabel: " Lead ", notes: " " } })
    expect((await t.query(internal.eventContacts.getPrimaryClients, { eventIds: [event.id] }))[event.id]?.contactId).toBe(a.contactId)
    expect(await t.mutation(internal.eventContacts.update, { id: a.id, patch: { isPrimary: false } })).toMatchObject({ isPrimary: false, roleLabel: "Lead", notes: null })
    await t.mutation(internal.eventContacts.remove, { id: a.id })
    await expect(t.mutation(internal.eventContacts.setPrimary, { id: a.id })).rejects.toMatchObject({ data: { code: "InvalidInput" } })
    await expect(t.mutation(internal.eventContacts.update, { id: a.id, patch: {} })).rejects.toThrow()
    expect(await t.query(internal.eventContacts.getPrimaryClients, { eventIds: [] })).toEqual({})
  })
  it("changes categories, rejects duplicate/category misuse and rolls back shared contact edits", async () => {
    const { t, event, category } = await setup()
    const next = await t.mutation(internal.vendorCategories.create, { input: { key: "next", label: "Next", colorToken: "sky" } })
    const a = await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { newContact: { displayName: "Vendor" } }, role: "vendor", opts: { vendorCategoryId: category.id } })
    await t.mutation(internal.eventContacts.updateWithContact, { id: a.id, contactPatch: { phone: "123" }, assignmentPatch: { vendorCategoryId: next.id, notes: "Changed" } })
    expect((await t.query(internal.contacts.getById, { id: a.contactId }))?.phone).toBe("123")
    expect(await t.query(internal.contactRoles.listForContact, { contactId: a.contactId })).toHaveLength(2)
    await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { contactId: a.contactId }, role: "vendor", opts: { vendorCategoryId: category.id } })
    await expect(t.mutation(internal.eventContacts.updateWithContact, { id: a.id, contactPatch: { phone: "456" }, assignmentPatch: { vendorCategoryId: category.id } })).rejects.toMatchObject({ data: { code: "DuplicateAssignment" } })
    expect((await t.query(internal.contacts.getById, { id: a.contactId }))?.phone).toBe("123")
    await expect(t.mutation(internal.eventContacts.update, { id: a.id, patch: { vendorCategoryId: null } })).rejects.toMatchObject({ data: { code: "InvalidRoleCategory" } })
    await expect(t.mutation(internal.vendorCategories.update, { id: next.id, patch: { key: "changed" } })).rejects.toThrow()
    // @ts-expect-error Assignment parents are immutable.
    await expect(t.mutation(internal.eventContacts.update, { id: a.id, patch: { contactId: a.contactId } })).rejects.toThrow()
  })
  it("resolves recipients in panel order, deduplicates email, skips missing email and isolates selections", async () => {
    const { t, event, other, category } = await setup()
    const a = await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { newContact: { displayName: "Client", email: "client@example.com" } }, role: "client" })
    const coordinator = await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { contactId: a.contactId }, role: "coordinator" })
    const vendor = await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { newContact: { displayName: "Vendor" } }, role: "vendor", opts: { vendorCategoryId: category.id } })
    const otherCategory = await t.mutation(internal.vendorCategories.create, { input: { key: "other_test", label: "Other", colorToken: "sky" } })
    const excluded = await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { newContact: { displayName: "Excluded", email: "excluded@example.com" } }, role: "vendor", opts: { vendorCategoryId: otherCategory.id } })
    const selection = { roles: ["client", "coordinator", "vendor"] as const, vendorCategoryIds: [category.id] }
    const result = await t.query(internal.eventContacts.resolveRecipients, { eventId: event.id, selection: { ...selection, roles: [...selection.roles] } })
    expect(result).toEqual({ recipients: [{ contactId: a.contactId, displayName: "Client", email: "client@example.com" }], skipped: [{ contactId: vendor.contactId, displayName: "Vendor" }] })
    expect(await t.query(internal.eventContacts.resolveRecipients, { eventId: other.id, selection: { eventContactIds: [a.id] } })).toEqual({ recipients: [], skipped: [] })
    expect(await t.query(internal.eventContacts.resolveRecipients, { eventId: event.id, selection: { eventContactIds: [a.id, coordinator.id] } })).toMatchObject({ recipients: result.recipients, skipped: [] })
    await t.mutation(internal.eventContacts.remove, { id: excluded.id })
    expect((await t.query(internal.eventContacts.resolveRecipients, { eventId: event.id, selection: { roles: ["vendor"] } })).recipients).toEqual([])
    expect(await t.query(internal.eventContacts.resolveRecipients, { eventId: event.id, selection: { roles: [] } })).toEqual({ recipients: [], skipped: [] })
  })
  it("rejects missing parents/assignments and never leaves inline contacts behind", async () => {
    const { t, event, category } = await setup()
    const c = await t.mutation(internal.contacts.create, { input: { displayName: "Deleted" } })
    const assignment = await t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { contactId: c.id }, role: "client" })
    await t.mutation(internal.events.remove, { id: event.id })
    await t.mutation(internal.contacts.remove, { id: c.id })
    await expect(t.query(internal.eventContacts.getPanel, { eventId: event.id })).rejects.toMatchObject({ data: { code: "NotFound" } })
    await expect(t.mutation(internal.eventContacts.assign, { eventId: event.id, target: { newContact: { displayName: "Orphan" } }, role: "client" })).rejects.toThrow()
    await expect(t.mutation(internal.eventContacts.remove, { id: assignment.id })).rejects.toMatchObject({ data: { code: "NotFound" } })
    await expect(t.mutation(internal.eventContacts.setPrimary, { id: assignment.id })).rejects.toThrow()
    await expect(t.mutation(internal.eventContacts.updateWithContact, { id: assignment.id, contactPatch: {}, assignmentPatch: {} })).rejects.toThrow()
    await expect(t.query(internal.eventContacts.listEventsForContact, { contactId: c.id })).rejects.toThrow()
    await expect(t.query(internal.eventContacts.resolveRecipients, { eventId: event.id, selection: { roles: [] } })).rejects.toThrow()
    await expect(t.mutation(internal.eventContacts.reorder, { eventId: event.id, role: "client", orderedIds: [] })).rejects.toThrow()
    await expect(t.mutation(internal.contactRoles.ensure, { contactId: c.id, role: "client" })).rejects.toMatchObject({ data: { code: "NotFound" } })
    const other = await t.mutation(internal.events.create, { input: {} })
    await expect(t.mutation(internal.eventContacts.assign, { eventId: other.id, target: { contactId: c.id }, role: "client" })).rejects.toThrow()
    await t.run(ctx => ctx.db.delete("vendorCategories", category.id))
    await expect(t.mutation(internal.eventContacts.assign, { eventId: other.id, target: { newContact: { displayName: "Orphan" } }, role: "vendor", opts: { vendorCategoryId: category.id } })).rejects.toThrow()
    expect((await t.query(internal.contacts.search, { limit: 100 })).items).toEqual([])
  })

})
